package animauxPlante.impl;

import animauxPlante.*;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultBranche <br>
 * @version generated on Sat Sep 30 17:35:42 BRT 2017 by romane
 */
public class DefaultBranche extends WrappedIndividualImpl implements Branche {

    public DefaultBranche(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





}
