package animauxPlante;

import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLClass;
import org.semanticweb.owlapi.model.OWLDataFactory;
import org.semanticweb.owlapi.model.OWLDataProperty;
import org.semanticweb.owlapi.model.OWLObjectProperty;

/**
 * Vocabulary class to provide access to the Manchester OWL API representatives for 
 * various entities in the ontology used to generate this code.<p> 
 * 
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: ${javaClass}
 *
 * @version generated on Sat Sep 30 17:35:42 BRT 2017 by romane
 */

public class Vocabulary {

	private static final OWLDataFactory factory = OWLManager.createOWLOntologyManager().getOWLDataFactory();

    /* ***************************************************
     * Class http://www.semanticweb.org/romane/ontologies/2017/8/AnimauxPlantes.owl#Animal
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ANIMAL.<p>
     * 
     */
    public static final OWLClass CLASS_ANIMAL = factory.getOWLClass(IRI.create("http://www.semanticweb.org/romane/ontologies/2017/8/AnimauxPlantes.owl#Animal"));

    /* ***************************************************
     * Class http://www.semanticweb.org/romane/ontologies/2017/8/AnimauxPlantes.owl#Arbre
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ARBRE.<p>
     * 
     */
    public static final OWLClass CLASS_ARBRE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/romane/ontologies/2017/8/AnimauxPlantes.owl#Arbre"));

    /* ***************************************************
     * Class http://www.semanticweb.org/romane/ontologies/2017/8/AnimauxPlantes.owl#Branche
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BRANCHE.<p>
     * 
     */
    public static final OWLClass CLASS_BRANCHE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/romane/ontologies/2017/8/AnimauxPlantes.owl#Branche"));

    /* ***************************************************
     * Class http://www.semanticweb.org/romane/ontologies/2017/8/AnimauxPlantes.owl#Carnivore
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CARNIVORE.<p>
     * 
     */
    public static final OWLClass CLASS_CARNIVORE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/romane/ontologies/2017/8/AnimauxPlantes.owl#Carnivore"));

    /* ***************************************************
     * Class http://www.semanticweb.org/romane/ontologies/2017/8/AnimauxPlantes.owl#Feuille
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class FEUILLE.<p>
     * 
     */
    public static final OWLClass CLASS_FEUILLE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/romane/ontologies/2017/8/AnimauxPlantes.owl#Feuille"));

    /* ***************************************************
     * Class http://www.semanticweb.org/romane/ontologies/2017/8/AnimauxPlantes.owl#Girafe
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class GIRAFE.<p>
     * 
     */
    public static final OWLClass CLASS_GIRAFE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/romane/ontologies/2017/8/AnimauxPlantes.owl#Girafe"));

    /* ***************************************************
     * Class http://www.semanticweb.org/romane/ontologies/2017/8/AnimauxPlantes.owl#Herbivore
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class HERBIVORE.<p>
     * 
     */
    public static final OWLClass CLASS_HERBIVORE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/romane/ontologies/2017/8/AnimauxPlantes.owl#Herbivore"));

    /* ***************************************************
     * Class http://www.semanticweb.org/romane/ontologies/2017/8/AnimauxPlantes.owl#Lion
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LION.<p>
     * 
     */
    public static final OWLClass CLASS_LION = factory.getOWLClass(IRI.create("http://www.semanticweb.org/romane/ontologies/2017/8/AnimauxPlantes.owl#Lion"));

    /* ***************************************************
     * Class http://www.semanticweb.org/romane/ontologies/2017/8/AnimauxPlantes.owl#Plante
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PLANTE.<p>
     * 
     */
    public static final OWLClass CLASS_PLANTE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/romane/ontologies/2017/8/AnimauxPlantes.owl#Plante"));

    /* ***************************************************
     * Class http://www.semanticweb.org/romane/ontologies/2017/8/AnimauxPlantes.owl#PlanteSavoureuse
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PLANTESAVOUREUSE.<p>
     * 
     */
    public static final OWLClass CLASS_PLANTESAVOUREUSE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/romane/ontologies/2017/8/AnimauxPlantes.owl#PlanteSavoureuse"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/romane/ontologies/2017/8/AnimauxPlantes.owl#mange
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property MANGE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_MANGE = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/romane/ontologies/2017/8/AnimauxPlantes.owl#mange"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/romane/ontologies/2017/8/AnimauxPlantes.owl#mangePar
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property MANGEPAR.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_MANGEPAR = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/romane/ontologies/2017/8/AnimauxPlantes.owl#mangePar"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/romane/ontologies/2017/8/AnimauxPlantes.owl#partieDe
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property PARTIEDE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_PARTIEDE = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/romane/ontologies/2017/8/AnimauxPlantes.owl#partieDe"));


}
